### ISSUE TITLE
Can't access repos inside organisation with a different name than the username

### ISSUE THREAD

**Issue by kimapril9** [heussd/mirror-to-bitbucket-github-action#2]
Is it possible that we have organisation name and user name parameters instead of username being used for space and user?

**Comment by heussd** [comment]
Sure, I can add more parameters to support this.

In order to develop and test this feature, could you please provide me more info about your setup? Looks like I don't have such a "organisation" in my free Bitbucket account. You could potentially also provide me a demo repository which I could use to develop the support for.

**Comment by heussd** [comment]
Thanks for inviting me to your private repo. This helped me understand your feature request.

Please check out the [latest version](https://github.com/marketplace/actions/mirror-to-bitbucket-github-action) of the action. I added support for specifying a space name of the repo other than a user name.

Please send me feedback if this solves your request.

**Comment by kimapril9** [comment]
That worked really well. Thanks mate!
